Fix lost reactivity.
js-tasks-ru/vue-20230905_gubinas83 pull request #5
Opened 2023-10-15 16:38 UTC by Svetlana-Gubina

Fix lost reactivity.

2023-10-15 16:39 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-15 16:44 UTC, ShGKme requested changes

2023-10-15 16:44 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> -</style>
Этому компоненту нужны стили, и их наличие не поможет с проблемой реактивности в другой задаче :)

2023-10-15 16:44 UTC, ShGKme commented on 08-reactivity/01-reactivity-losing/components/SensorsDataView.vue
> +      this.sensors = this.sensorsDataController.getData();
Это решение визуально вроде работает, но не совсем корректно. Оно не решает проблему реактивности данных, а удаляет их и позже вновь добавляет.

Метод `getData` не возвращает данные, а запрашивает асинхронное получение данных, обработка получения которых будет в другом коллбеке.

В итоге здесь просто в `this.sensors` присваивается `undefined`. А через секунду, когда данные приходят, снова заменяется на данные.

Это приводит к мельканию интерфейса, вместо обновления чисел в таблице каждую секунду компонент мелькает, уходя в состояние загрузки данных.

2023-10-18 12:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-25 16:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-25 18:35 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> -</style>
Эти стили нужно вернуть. Они пригодятся при использовании этого компонента в дальнейших задачах и проекте.

2023-11-29 16:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-01 19:37 UTC, ShGKme approved these changes
Компонент `UiInput` остался без стилей

2023-12-01 19:37 UTC, merged